# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='has_been_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
