# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_has_been_fetched'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=10000)),
            ],
        ),
    ]
