# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_corenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.CharField(default=b'EN', max_length=4),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
