# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import re

def forward(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    News = apps.get_model("news", "News")
    for news in News.objects.all():
        if not news.source:
            domain = re.search('.*([^\.]+)(com|net|org|info|coop|int|co\.uk|org\.uk|ac\.uk|uk|__and so on__)$', news.description)
            if domain:
                news.source = domain.group(0)
                news.save()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_corenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.RunPython(forward, reverse),
    ]
