# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 19:55
from __future__ import unicode_literals

from django.db import migrations
import re

def add_domain(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    News = apps.get_model('news', 'News')
    for n in News.objects.all():
        se = re.search(ur'^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)', n.description)
        if se:
            n.domain = se.group(1)
        n.save()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161110_2130'),
    ]

    operations = [
        migrations.RunPython(add_domain),
    ]
