# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170604_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='domain',
            field=models.CharField(default=b'unkown', max_length=100),
        ),
    ]
