# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
