# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
