# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20151203_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_picture',
            field=models.CharField(max_length=200),
        ),
    ]
