# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20151203_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
