# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='/static/blog/img/'),
        ),
    ]
