# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='region',
            field=models.CharField(default=b'EN', max_length=4),
        ),
    ]
